# Learning numpy,matplotlib and scikit learn

In [2]:
import numpy as np

In [6]:
# Gives random values between 0 to 1
arr=np.random.rand(5)
print(arr)

[0.14013077 0.41480463 0.2572501  0.05710251 0.33834618]


In [9]:
# np.array
a=np.array([1,2,3])
b=np.array([[1,2,3],[4,5,6]])
c=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(b)
print(c)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:

print(a.shape) #shape of the array
print(a.ndim)
print(a.size)

(3,)
1
3


In [ ]:
print(np.zeros((3,3)))
# print(np.eye(7))
print(np.arange(0,10,2))
print(np.linspace(0,1,5)
print(np.full((5,5),5))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]
