# Learning numpy,matplotlib and scikit learn

In [2]:
import numpy as np

In [6]:
# Gives random values between 0 to 1
arr=np.random.rand(5)
print(arr)

[0.14013077 0.41480463 0.2572501  0.05710251 0.33834618]


In [9]:
# np.array
a=np.array([1,2,3])
b=np.array([[1,2,3],[4,5,6]])
c=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(b)
print(c)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:

print(a.shape) #shape of the array
print(a.ndim)
print(a.size)

(3,)
1
3


In [ ]:
print(np.zeros((3,3)))
# print(np.eye(7))
print(np.arange(0,10,2))
print(np.linspace(0,1,5)
print(np.full((5,5),5))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [31]:
np.random.seed(0)
arr=np.random.rand(3,3)
print(arr)
print(np.random.randint(100,200,10))

[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]
 [0.43758721 0.891773   0.96366276]]
[158 165 139 187 146 188 181 137 125 177]


In [ ]:
arr1=np.array([2,3])
arr2=np.array([4,5])
print(arr1+arr2)
print(arr1*arr2)
print(arr1-arr2)


[6 8]
[ 8 15]
[-2 -2]


In [ ]:
# Dot Product 
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.dot(a,b))
# For 2d Array matrix multiplication wil take place


32


In [36]:
arr = np.array([1,2,3,4,5])
print(np.sum(arr))       # sum
print(np.mean(arr))      # average
print(np.std(arr))       # standard deviation
print(np.max(arr))       # maximum
print(np.min(arr))       # minimum


15
3.0
1.4142135623730951
5
1


In [38]:
print(np.mean([68, 71, 72, 69, 70]))

70.0


## Starting Matplotlib

In [1]:
import matplotlib as plt